# Generated by Django 2.2.16 on 2020-09-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.AddField(
            model_name='customtext',
            name='priceField',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='productImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='productName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
